### ISSUE TITLE
Whisperfish sometimes crashes when opening notification from notification screen

### ISSUE THREAD

**Issue by rodneyrod** [aebruno/whisperfish#75] opened 2017-03-21 03:16 UTC
Not all the time, but sometimes when you click on the notification nothing happens, and going to the opened apps screen shows Whisperfish greyed out, signifying that it isn't running.
Tapping on it just launches the app again.

**Comment by bonanza123** [comment] 2017-03-21 07:23
dupe of https://github.com/aebruno/whisperfish/issues/57 ?

**Comment by aebruno** [comment] 2017-03-21 12:12
I have seen this behavior as well but have not been able to reproduce. If you can consistently reproduce this let me know and I'll try and track it down.

**Closed** 2020-11-19 16:31 UTC
