### ISSUE TITLE
Cannot register/no call from Signal

### ISSUE THREAD

**Issue by rubdos** [aebruno/whisperfish#114] opened 2018-05-10 13:56 UTC
Hi!

I've tried this with 0.5.1, 0.5.0, 0.4.5, three times with clean `{.config,.local/share}/harbour-whisperfish`.

1. Enter (new) password
2. Enter phone number (+324****). The + doesn't appear, but it seems to be in the log
3. Wait for a call that does not come.

I also tried with 00324****, but then the log shows "invalid country code".

[log.txt](https://github.com/aebruno/whisperfish/files/1991874/log.txt)

**Comment by d9h20f** [comment] 2018-05-11 11:15
Possible duplicate of https://github.com/aebruno/whisperfish/issues/91 by @objectifnul, also with a Belgian phone number.

**Comment by rubdos** [comment] 2018-05-11 14:35
Sounds like it. Is it useful to keep this issue open then? @objectifnul, FYI, my operator is Mobile Vikings.

**Comment by rubdos** [comment] 2018-05-11 17:35
[I posted a workaround on TJC](https://together.jolla.com/question/181042/whisperfish-device-verification-code/?answer=183784#post-id-183784).

**Closed** 2020-11-19 16:30 UTC
