### ISSUE TITLE
Whisperfish crashes after Login

### ISSUE THREAD

**Issue by fletchers** [aebruno/whisperfish#79] opened 2017-04-11 08:05 UTC
Hey,

symptoms as follows:
-I login with correct information.
-Screen changes to main screen, I can see recent message history etc., so I'm logged in. Halts for a few frames during transitioning between the two screens.
-After about 3-5 seconds, throws me out to sfos home screen, having to login when restarting the app.

I'm using community ported sfOS on the oneplus x. However, I haven't had that problem thus far, could use the app just fine until today.

Maybe OWS is throwing me out? On the sailsecure this approach of theirs was mentioned after all.

Greetings,
fletchers

**Comment by DanScharon** [comment] 2017-04-11 08:06
duplicate of #78

**Comment by oleid** [comment] 2017-04-11 14:37
Are you using v0.4.3? Upgrading to that version helped me. What do you get in /tmp/whisperfish-app.log and on commandline when running "harbour-whisperfish -d"?

**Comment by withju** [comment] 2017-04-13 13:55
Hello,
I have the same problem, until last week everything worked great.
I'm running SF 2.0.5.6 on fairphone2

**Closed** 2018-03-23 02:50 UTC
